# Generated by Django 4.1.7 on 2023-07-08 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelBud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10)])),
                ('travel_date', models.DateField()),
                ('stay_duration', models.PositiveIntegerField(null=True)),
                ('city', models.CharField(max_length=100)),
                ('adult', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('children', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='travel_date',
            field=models.DateField(null=True),
        ),
    ]
