# Generated by Django 4.1.7 on 2023-07-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_travelbud_alter_user_contact_alter_user_travel_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='travelbud',
            table='Travelers',
        ),
    ]
